shadowsocks:
  image: shadowsocks/shadowsocks-libev
  ports:
    - "127.0.0.1:45567:8388/tcp"
    - "127.0.0.1:45567:8388/udp"
  environment:
    - METHOD=aes-256-gcm
    - PASSWORD=9MLSpPmNt
  restart: always
